=== echiu64/gutenprint/src/main/gimpprint.xsd
<?xml version="1.0"?>                  <!-- -*- mode: xml -*- -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://gimp-print.sourceforge.net/xsd/gp.xsd-1.0"
xmlns="http://gimp-print.sourceforge.net/xsd/gp.xsd-1.0"
elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Schema for Gimp-Print XML data
      Requires Gimp-Print 4.3 or later
      Based on printers.xml and printdef
      Author: Roger Leigh (roger@whinlatter.uklinux.net)
      $Id$
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="gimp-print">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="printdef" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="paperdef" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="printdef">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="family" minOccurs="0"
	maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="family">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="printer" minOccurs="0"
	maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:attributeGroup>
      <xsd:attribute name="name" type="normalizedString" use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="printer">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="color" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="model" minOccurs="1" maxOccurs="1"/>
	<xsd:element ref="black" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="cyan" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="magenta" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="yellow" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="brightness" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="gamma" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="density" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="saturation" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="blackdensity" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="cyandensity" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="magentadensity" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="yellowdensity" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="gcrlower" minOccurs="0" maxOccurs="1"/>
	<xsd:element ref="gcrupper" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:attributeGroup>
      <xsd:attribute name="name" type="normalizedString" use="required"/>
      <xsd:attribute name="driver" type="token" use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="color">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="boolean" default="false"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="model">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="positiveInteger" use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="black">
    <xsd:attributeGroup ref="colorattrs" use="required"/>
  </xsd:element>
  <xsd:element name="cyan">
    <xsd:attributeGroup ref="colorattrs" use="required"/>
  </xsd:element>
  <xsd:element name="magenta">
    <xsd:attributeGroup ref="colorattrs" use="required"/>
  </xsd:element>
  <xsd:element name="yellow">
    <xsd:attributeGroup ref="colorattrs" use="required"/>
  </xsd:element>
  <xsd:element name="brightness">
    <xsd:attributeGroup ref="brightnessattrs" use="required"/>
  </xsd:element>
  <xsd:element name="contrast">
    <xsd:attributeGroup ref="colorattrs" use="required"/>
  </xsd:element>
  <xsd:element name="gamma">
    <xsd:attributeGroup ref="gammaattrs" use="required"/>
  </xsd:element>
  <xsd:element name="density">
    <xsd:attributeGroup ref="densityattrs" use="required"/>
  </xsd:element>
  <xsd:element name="saturation">
    <xsd:attributeGroup ref="saturationattrs" use="required"/>
  </xsd:element>
  <xsd:element name="blackdensity">
    <xsd:attributeGroup ref="densityattrs" use="required"/>
  </xsd:element>
  <xsd:element name="cyandensity">
    <xsd:attributeGroup ref="densityattrs" use="required"/>
  </xsd:element>
  <xsd:element name="magentadensity">
    <xsd:attributeGroup ref="densityattrs" use="required"/>
  </xsd:element>
  <xsd:element name="yellowdensity">
    <xsd:attributeGroup ref="densityattrs" use="required"/>
  </xsd:element>
  <xsd:element name="gcrlower">
    <xsd:attributeGroup ref="gcrlowerattrs" use="required"/>
  </xsd:element>
  <xsd:element name="gcrupper">
    <xsd:attributeGroup ref="gcrupperattrs" use="required"/>
  </xsd:element>
  <xsd:element name="paperdef">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="paper" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="paper">
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element name="description" minOccurs="1" maxOccurs="1"/>
	<xsd:element name="comment" minOccurs="1" maxOccurs="1"/>
	<xsd:element name="width" minOccurs="1" maxOccurs="1"/>
	<xsd:element name="height" minOccurs="1" maxOccurs="1"/>
	<xsd:element name="unit" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:attributeGroup>
      <xsd:attribute name="name" type="normalizedString"
	use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="description">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="normalizedString"
	use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="comment">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="normalizedString"
	use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="width">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="positiveInteger" use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="height">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="positiveInteger" use="required"/>
    </xsd:attributeGroup>
  </xsd:element>
  <xsd:element name="unit">
    <xsd:attributeGroup>
      <xsd:attribute name="value" type="normalizedString"
	use="required"/>
    </xsd:attributeGroup>
  </xsd:element>

  <xsd:attributeGroup name="colorattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="1.00">
	  <xsd:minInclusive value="0.00"/>
	  <xsd:maxInclusive value="4.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="brightnessattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="1.00">
	  <xsd:minInclusive value="0.00"/>
	  <xsd:maxInclusive value="2.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="densityattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="1.00">
	  <xsd:minInclusive value="0.10"/>
	  <xsd:maxInclusive value="2.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="gammaattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="1.00">
	  <xsd:minInclusive value="0.10"/>
	  <xsd:maxInclusive value="4.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="saturationattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="1.00">
	  <xsd:minInclusive value="0.00"/>
	  <xsd:maxInclusive value="9.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="gcrlowerattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="0.2">
	  <xsd:minInclusive value="0.00"/>
	  <xsd:maxInclusive value="1.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>
  <xsd:attributeGroup name="gcrupperattrs">
    <xsd:attribute name="value">
      <xsd:simpleType>
	<xsd:restriction base="xsd:float" default="0.5">
	  <xsd:minInclusive value="0.00"/>
	  <xsd:maxInclusive value="5.00"/>
	</xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:attributeGroup>

</xsd:schema>

=== echiu64/gutenprint/src/main/printers.xml
<?xml version="1.0"?>

<!--
   XML description of printers known to libgimpprint
   This file was originally generated.  It should be edited by hand.

   "$Id$"
-->

<gimp-print xmlns="http://gimp-print.sourceforge.net/xsd/gp.xsd-1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://gimp-print.sourceforge.net/xsd/gp.xsd-1.0 gimpprint.xsd">
  <printdef>
    <family name="ps">
      <printer name="PostScript Level 1" driver="ps" manufacturer="Adobe">
        <model value="0"/>
        <gamma value="1.000"/>
        <density value="1.000"/>
      </printer>
      <printer name="PostScript Level 2" driver="ps2" manufacturer="Adobe">
        <model value="1"/>
        <gamma value="1.000"/>
        <density value="1.000"/>
      </printer>
    </family>
    <family name="canon">
      <printer name="Canon BJC 30" driver="bjc-30" manufacturer="Canon">
        <model value="30"/>
        <gamma value="2.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 50" driver="bjc-50" manufacturer="Canon">
        <model value="4400"/>
        <gamma value="0.5"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 55" driver="bjc-55" manufacturer="Canon">
        <model value="4400"/>
        <gamma value="0.5"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 80" driver="bjc-80" manufacturer="Canon">
        <model value="4400"/>
        <gamma value="0.5"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 85" driver="bjc-85" manufacturer="Canon">
        <model value="85"/>
        <gamma value="0.5"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 210" driver="bjc-210" manufacturer="Canon">
        <model value="210"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 240" driver="bjc-240" manufacturer="Canon">
        <model value="240"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 250" driver="bjc-250" manufacturer="Canon">
        <model value="250"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 1000" driver="bjc-1000" manufacturer="Canon">
        <model value="1000"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 2000" driver="bjc-2000" manufacturer="Canon">
        <model value="2000"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 3000" driver="bjc-3000" manufacturer="Canon">
        <model value="3000"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 4300" driver="bjc-4300" manufacturer="Canon">
        <model value="4300"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
      <printer name="Canon BJC 4400 photo" driver="bjc-4400" manufacturer="Canon">
        <model value="4400"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 6000" driver="bjc-6000" manufacturer="Canon">
        <model value="6000"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
      <printer name="Canon BJC 6100" driver="bjc-6100" manufacturer="Canon">
        <model value="6100"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 6200" driver="bjc-6200" manufacturer="Canon">
        <model value="6200"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
      <printer name="Canon BJC 6500" driver="bjc-6500" manufacturer="Canon">
        <model value="6500"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
      <printer name="Canon BJC 7000" driver="bjc-7000" manufacturer="Canon">
        <model value="7000"/>
        <gamma value="0.600"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 7100" driver="bjc-7100" manufacturer="Canon">
        <model value="7100"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon BJC 8200" driver="bjc-8200" manufacturer="Canon">
        <model value="8200"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon S400" driver="bjc-s400" manufacturer="Canon">
        <model value="3000"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon S450" driver="bjc-s450" manufacturer="Canon">
        <model value="6200"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
      <printer name="Canon S800" driver="bjc-s800" manufacturer="Canon">
        <model value="8200"/>
        <gamma value="1.000"/>
        <density value="0.800"/>
      </printer>
      <printer name="Canon S4500" driver="bjc-s4500" manufacturer="Canon">
        <model value="6500"/>
        <gamma value="0.750"/>
        <density value="1.000"/>
      </printer>
    </family>
    <family name="escp2">
      <printer name="EPSON Stylus C20SX" driver="escp2-c20sx" manufacturer="Epson">
        <model value="42"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C20UX" driver="escp2-c20ux" manufacturer="Epson">
        <model value="42"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C40SX" driver="escp2-c40sx" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C40UX" driver="escp2-c40ux" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C41SX" driver="escp2-c41sx" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C41UX" driver="escp2-c41ux" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C42SX" driver="escp2-c42sx" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C42UX" driver="escp2-c42ux" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C43SX" driver="escp2-c43sx" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C43UX" driver="escp2-c43ux" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C44SX" driver="escp2-c44sx" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C44UX" driver="escp2-c44ux" manufacturer="Epson">
        <model value="43"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C50" driver="escp2-c50" manufacturer="Epson">
        <model value="56"/>
        <magenta value="0.95"/>
        <yellow value="0.9"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C60" driver="escp2-c60" manufacturer="Epson">
        <model value="33"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C61" driver="escp2-c61" manufacturer="Epson">
        <model value="52"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C62" driver="escp2-c62" manufacturer="Epson">
        <model value="52"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C63" driver="escp2-c63" manufacturer="Epson">
        <model value="61"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C64" driver="escp2-c64" manufacturer="Epson">
        <model value="61"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C70" driver="escp2-c70" manufacturer="Epson">
        <model value="44"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C80" driver="escp2-c80" manufacturer="Epson">
        <model value="44"/>
        <gamma value="0.731"/>
        <density value="1.0"/>
      </printer>
      <printer name="EPSON Stylus C82" driver="escp2-c82" manufacturer="Epson">
